In [9]:
import pandas as pd
import csv
import numpy as np
wines = pd.read_csv('C:\\Users\\exam2\\Downloads\\winequality-red.csv')

In [107]:
wines = np.genfromtxt('C:\\Users\\exam2\\Downloads\\winequality-red.csv',dtype=float,delimiter=';',skip_header=1)
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [31]:
wines.shape

(1599, 12)

In [32]:
wines[3][4]

0.075

In [34]:
print(wines[:3,3])

[1.9 2.6 2.3]


In [48]:
print(wines[:,2])

[0.   0.   0.04 ... 0.13 0.12 0.47]


In [49]:
print(wines[3])

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


In [51]:
wines[1,5] = 10

In [60]:
slice_new = wines[:,9]
slice_new[:] = 666 
slice_new

array([666., 666., 666., ..., 666., 666., 666.])

In [61]:
print(wines)

[[7.40e+00 7.00e-01 0.00e+00 ... 6.66e+02 9.40e+00 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.66e+02 9.80e+00 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.66e+02 9.80e+00 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 6.66e+02 1.10e+01 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 6.66e+02 1.02e+01 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.66e+02 1.10e+01 6.00e+00]]


In [99]:
print(wines.dtype)
wines.astype(int)

float64


array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

In [87]:
wines[:,-1] += 10
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  , 15.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  , 15.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  , 15.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   , 16.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  , 15.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   , 16.   ]])

In [100]:
print('sum of array : ',np.sum(wines))
print('row wise : ',np.sum(wines,axis = 1))
print('column wise : ',np.sum(wines,axis=0))

sum of array :  152084.78194
row wise :  [ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]
column wise :  [13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [101]:
wines[:,-1] += wines[:,-1]
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  , 10.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  , 10.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  , 10.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   , 12.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  , 10.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   , 12.   ]])

In [102]:
wines[:,-2] *= wines[:,-1]
print(wines)

[[7.40e+00 7.00e-01 0.00e+00 ... 5.60e-01 9.40e+01 1.00e+01]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.80e-01 9.80e+01 1.00e+01]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.50e-01 9.80e+01 1.00e+01]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 7.50e-01 1.32e+02 1.20e+01]
 [5.90e+00 6.45e-01 1.20e-01 ... 7.10e-01 1.02e+02 1.00e+01]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.60e-01 1.32e+02 1.20e+01]]


In [111]:
np.where(wines[:,-1]>5)

(array([   3,    7,    8,   16,   19,   20,   24,   29,   31,   33,   35,
          36,   37,   42,   51,   52,   54,   59,   62,   69,   70,   77,
          84,   86,   91,   95,   99,  100,  101,  102,  108,  113,  115,
         116,  117,  118,  119,  121,  128,  133,  134,  142,  144,  148,
         149,  150,  159,  162,  168,  171,  172,  173,  177,  184,  191,
         197,  198,  200,  204,  205,  206,  209,  210,  211,  212,  214,
         220,  223,  225,  226,  228,  230,  231,  232,  234,  235,  236,
         237,  238,  239,  241,  242,  243,  244,  245,  248,  249,  250,
         251,  254,  259,  265,  267,  268,  269,  270,  271,  275,  276,
         277,  278,  279,  280,  281,  283,  286,  287,  288,  290,  292,
         293,  294,  300,  301,  305,  307,  308,  309,  310,  311,  312,
         315,  317,  318,  319,  320,  323,  324,  325,  326,  328,  330,
         331,  332,  334,  335,  336,  338,  339,  340,  341,  342,  343,
         344,  346,  347,  348,  349, 

In [112]:
np.where(wines[:,-1]==10)

(array([], dtype=int64),)

In [110]:
wines[wines[:,-1]>7]

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 8.6000e-01,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 8.2000e-01,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 8.2000e-01,
        1.2900e+01, 8.0000e+00],
       [1.2600e+01, 3.1000e-01, 7.2000e-01, 2.2000e+00, 7.2000e-02,
        6.0000e+00, 2.9000e+01, 9.9870e-01, 2.8800e+00, 8.2000e-01,
        9.8000e+00, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.9000e-01,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 9.2000e-01,
        1.1700e+01,

In [120]:

wines[np.where((wines[:,-2]>10) & (wines[:,-1]>7))]

array([[7.9000e+00, 3.5000e-01, 4.6000e-01, 3.6000e+00, 7.8000e-02,
        1.5000e+01, 3.7000e+01, 9.9730e-01, 3.3500e+00, 8.6000e-01,
        1.2800e+01, 8.0000e+00],
       [1.0300e+01, 3.2000e-01, 4.5000e-01, 6.4000e+00, 7.3000e-02,
        5.0000e+00, 1.3000e+01, 9.9760e-01, 3.2300e+00, 8.2000e-01,
        1.2600e+01, 8.0000e+00],
       [5.6000e+00, 8.5000e-01, 5.0000e-02, 1.4000e+00, 4.5000e-02,
        1.2000e+01, 8.8000e+01, 9.9240e-01, 3.5600e+00, 8.2000e-01,
        1.2900e+01, 8.0000e+00],
       [1.1300e+01, 6.2000e-01, 6.7000e-01, 5.2000e+00, 8.6000e-02,
        6.0000e+00, 1.9000e+01, 9.9880e-01, 3.2200e+00, 6.9000e-01,
        1.3400e+01, 8.0000e+00],
       [9.4000e+00, 3.0000e-01, 5.6000e-01, 2.8000e+00, 8.0000e-02,
        6.0000e+00, 1.7000e+01, 9.9640e-01, 3.1500e+00, 9.2000e-01,
        1.1700e+01, 8.0000e+00],
       [1.0700e+01, 3.5000e-01, 5.3000e-01, 2.6000e+00, 7.0000e-02,
        5.0000e+00, 1.6000e+01, 9.9720e-01, 3.1500e+00, 6.5000e-01,
        1.1000e+01,

In [121]:
wines.reshape(12,1599)

array([[7.40000e+00, 7.00000e-01, 0.00000e+00, ..., 6.60000e+00,
        5.00000e-01, 1.00000e-02],
       [1.50000e+00, 6.00000e-02, 1.70000e+01, ..., 3.30000e+00,
        9.60000e-02, 2.60000e+01],
       [6.10000e+01, 1.00025e+00, 3.60000e+00, ..., 4.20000e+01,
        9.96300e-01, 3.10000e+00],
       ...,
       [2.30000e+00, 7.60000e-02, 2.30000e+01, ..., 1.70000e+00,
        7.50000e-02, 6.00000e+00],
       [2.50000e+01, 9.95810e-01, 3.09000e+00, ..., 5.30000e+01,
        9.95800e-01, 3.41000e+00],
       [6.70000e-01, 9.70000e+00, 5.00000e+00, ..., 6.60000e-01,
        1.10000e+01, 6.00000e+00]])