In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [2]:
arr+1

array([2, 3, 4, 5, 6])

In [3]:
arr-1

array([0, 1, 2, 3, 4])

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]


In [6]:
matrix = np.ones([2,3,3])
print(matrix.shape)
print(matrix.ndim)

(2, 3, 3)
3


In [28]:
matrix = np.identity(3,dtype=int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
matrix.flatten()

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

In [15]:
matrix.reshape([1,9])

array([[1, 0, 0, 0, 1, 0, 0, 0, 1]])

In [39]:
matrix
row = np.array([1,2,3])
col = np.array([1,2,3])
print(np.vstack((matrix,row)))
print(np.hstack((matrix,col.reshape([len(col),1]))))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 2 3]]
[[1 0 0 1]
 [0 1 0 2]
 [0 0 1 3]]


In [45]:
matrix[1:,1:]

array([[1, 0],
       [0, 1]])

In [5]:
arr = np.array([1,2,3,4,5,6])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

6
1
3.5
3.5
1.707825127659933


In [11]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[6,5],[3,2]])
print(np.dot(mat1,mat2))
print(np.multiply(mat1,mat2))

[[12  9]
 [39 30]]
[[ 6 10]
 [12 10]]


matrix = np.array([[1,2,3,4],[5,6,7,8]])
matrix

In [16]:
matrix = np.array([[1,2,3],[5,6,7],[4,8,9]])
np.linalg.eig(matrix)

(array([16.58623849+0.j        , -0.29311924+0.79848134j,
        -0.29311924-0.79848134j]),
 array([[ 0.22456533+0.j        , -0.16240098+0.43130149j,
         -0.16240098-0.43130149j],
        [ 0.60905077+0.j        ,  0.692036  +0.j        ,
          0.692036  -0.j        ],
        [ 0.76067573+0.j        , -0.50615145-0.2291328j ,
         -0.50615145+0.2291328j ]]))

In [10]:
D = np.linalg.det([[3,1],[1,2]])
d1 = np.linalg.det([[9,1],[2,2]])
d2 = np.linalg.det([[3,1],[1,2]])
print(f'X0 = {round(d1/D)} and x1 = {round(d2/D)}')

X0 = 3 and x1 = 1


In [11]:
a = [[1,2,3],[4,5,6],[7,8,9]]
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [12]:
np.linalg.matrix_rank(a)

2

In [13]:
np.linalg.det(a)

-9.51619735392994e-16