In [3]:
import numpy as np
import pandas as pd

In [70]:
#1. Download the dataset winequality-red.csv file( each column is separated  by a semicolon (;)) from the UCI Machine Learning Repository.
arr = np.loadtxt(r"E:\Downloads\data-analysis\winequality-red.csv",delimiter=";", dtype=str,skiprows=1)
display(arr)

array([['7.4', '0.7', '0', ..., '0.56', '9.4', '5'],
       ['7.8', '0.88', '0', ..., '0.68', '9.8', '5'],
       ['7.8', '0.76', '0.04', ..., '0.65', '9.8', '5'],
       ...,
       ['6.3', '0.51', '0.13', ..., '0.75', '11', '6'],
       ['5.9', '0.645', '0.12', ..., '0.71', '10.2', '5'],
       ['6', '0.31', '0.47', ..., '0.66', '11', '6']], dtype='<U16')

In [71]:
#2. Convert it to numPy array, name it as wines (leave the first row of the list) and specify the data type of array as float.
wines=arr.astype('float64')
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [72]:
#3. Identify the shape of the array.
np.shape(wines)

(1599, 12)

In [13]:
#4. Display the element at row 3 and column 4.
wines[2,3]

2.3

In [48]:
#5. Display the first three items from the fourth column.
wines[:3,3]

array([1.9, 2.6, 2.3])

In [19]:
#6. Display third column from each row.
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [21]:
#7. Display fourth row.
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [73]:
#8. Assign value 10 to 2nd row and 6th column element.
wines[1,5] = 10
print(wines[1,5])

10.0


In [74]:
#9. Take the 10th column from wines array and name that slice as slice_new and assign value 666 to all elements of slice_new
slice_new = wines[:,9]
slice_new[:] = 666
print(slice_new)

[666. 666. 666. ... 666. 666. 666.]


In [75]:
#10. Display wines array.
print(wines)

[[7.40e+00 7.00e-01 0.00e+00 ... 6.66e+02 9.40e+00 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.66e+02 9.80e+00 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.66e+02 9.80e+00 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 6.66e+02 1.10e+01 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 6.66e+02 1.02e+01 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.66e+02 1.10e+01 6.00e+00]]


In [76]:
#11. Find the data type of wines array and Change the data type to int.
print(wines.dtype)
wines = wines.astype('int')
print(wines.dtype)
print(wines)

float64
int32
[[  7   0   0 ... 666   9   5]
 [  7   0   0 ... 666   9   5]
 [  7   0   0 ... 666   9   5]
 ...
 [  6   0   0 ... 666  11   6]
 [  5   0   0 ... 666  10   5]
 [  6   0   0 ... 666  11   6]]


In [77]:
#12. Add 10 points to each quality score.
wines[:-1] += 10
print(wines[:,-1])

[15 15 15 ... 16 15  6]


In [78]:
#13. Find the sum of all the elements in an array
print(wines.sum())
print(sum(sum(wines)))

1402158
1402158


In [79]:
#14. Find the sum of all the values in every column.
print(wines.sum(axis = 0))

[  28569   16004   15981   19330   15980   41347   90281   16061   20750
 1080914   31949   24992]


In [80]:
#15. Find the sum of all the values in every row.
print(wines.sum(axis = 1))

[856 889 881 ... 883 887 755]


In [81]:
#16. Add the quality column to itself
wines[:,-1] += wines[:,-1]
print(wines[:,-1])

[30 30 30 ... 32 30 12]


In [82]:
# 17. Multiply alcohol by quality
print(wines[:,-2]* wines[:,-1])

[570 570 570 ... 672 600 132]


In [83]:
# 18. Display which wines have a quality rating higher than 5.
print(wines[wines[:,-1]>5])

[[ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 ...
 [ 16  10  10 ... 676  21  32]
 [ 15  10  10 ... 676  20  30]
 [  6   0   0 ... 666  11  12]]


In [84]:
# 19. Check if any wines have a quality rating equal to 10.
print(wines[wines[:,-1]==10])

[]


In [85]:
# 20. Select rows in wines where the quality is over 7
print(wines[wines[:,-1]>7])

[[ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 ...
 [ 16  10  10 ... 676  21  32]
 [ 15  10  10 ... 676  20  30]
 [  6   0   0 ... 666  11  12]]


In [86]:
# 21. Display wines with alcohol greater than 10 and quality greater than 7.
print(wines[(wines[:,-2]>10) & (wines[:,-1]>7)])

[[ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 [ 17  10  10 ... 676  19  30]
 ...
 [ 16  10  10 ... 676  21  32]
 [ 15  10  10 ... 676  20  30]
 [  6   0   0 ... 666  11  12]]


In [87]:
# 22. Change the shape of wines array.
wines = wines.reshape((533,36))
print(wines.shape)

(533, 36)
